
// this test suite is generated by an LLM to simplify testing.


#include "IPBclientAPI.h"
#include "IPBtypes.h"
#include "IPBprotocol.h"
#include "IPBnetwork.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <assert.h>
#include <arpa/inet.h>
#include <sys/time.h>
#include <signal.h>

#define GREEN "\033[0;32m"
#define RED "\033[0;31m"
#define BLUE "\033[0;34m"
#define RESET "\033[0m"

#define SERVER_IP "127.0.0.1"
#define SERVER_PORT 9000
#define PASS_COMMON 1234

#define ID_ALICE "Alice001"
#define ID_BOB   "Bob00001"
#define ID_CHAR  "Char0001"
#define ID_DAVE  "Dave0001"

#define PORT_ALICE 5001
#define PORT_BOB 5002
#define PORT_CHARLIE 5003
#define PORT_DAVE 5004

IPBclientSession sessionA, sessionB, sessionC, sessionD;

void print_header(const char* title) { printf(BLUE "\n=== %s ===" RESET "\n", title); }

void assert_success(const char* testName, IPBstatus status) {
    if (status == IPB_OK) printf(GREEN " [PASS] %s" RESET "\n", testName);
    else { printf(RED " [FAIL] %s (Got %s)" RESET "\n", testName, IPBstatusToString(status)); exit(1); }
}

void assert_failure(const char* testName, IPBstatus status) {
    if (status != IPB_OK) printf(GREEN " [PASS] %s (Rejected)" RESET "\n", testName);
    else { printf(RED " [FAIL] %s (Command SUCCEEDED unexpected)" RESET "\n", testName); exit(1); }
}

// STRICT VERIFICATION: Exits on failure
void verify_udp_strict(int udpSocket, StreamCode expectedCode, const char* expectedHexCount) {
    char buffer[MAX_PACKET_SIZE];
    struct sockaddr_in from;
    socklen_t addrLen = sizeof(from);
    
    // Increased timeout to 3 seconds for robustness
    struct timeval tv = {3, 0}; 
    setsockopt(udpSocket, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

    int len = recvfrom(udpSocket, buffer, MAX_PACKET_SIZE, 0, (struct sockaddr*)&from, &addrLen);
    if (len < 0) {
        printf(RED " [FAIL] UDP Timeout (Expected Code %d)" RESET "\n", expectedCode);
        exit(1);
    }

    buffer[len] = '\0';
    int code = buffer[0] - '0';

    if (code != (int)expectedCode) {
        printf(RED " [FAIL] UDP Code Mismatch. Expected %d, Got %d" RESET "\n", (int)expectedCode, code);
        exit(1);
    }
    
    if (strcmp(buffer+1, expectedHexCount) != 0) {
         printf(RED " [FAIL] Hex Mismatch: Expected '%s', Got '%s'" RESET "\n", expectedHexCount, buffer+1);
         exit(1);
    }
}

int main() {
    signal(SIGPIPE, SIG_IGN);
    printf("==========================================\n");
    printf("      IPB ULTIMATE CERTIFICATION SUITE    \n");
    printf("==========================================\n");

    IPBstatus res;
    IPBpacket packet;

    // --- 1. SETUP ---
    print_header("1. Core Registration");
    IPBinitClientNetwork(&sessionA, SERVER_IP, SERVER_PORT, PORT_ALICE);
    IPBinitClientNetwork(&sessionB, SERVER_IP, SERVER_PORT, PORT_BOB);
    IPBinitClientNetwork(&sessionC, SERVER_IP, SERVER_PORT, PORT_CHARLIE);
    IPBinitClientNetwork(&sessionD, SERVER_IP, SERVER_PORT, PORT_DAVE);

    res = IPBregister(&sessionA, ID_ALICE, PORT_ALICE, PASS_COMMON);
    if(res==IPB_ERROR_USER_ALREADY_REGISTERED) IPBconnect(&sessionA, ID_ALICE, PASS_COMMON);
    
    res = IPBregister(&sessionB, ID_BOB, PORT_BOB, PASS_COMMON);
    if(res==IPB_ERROR_USER_ALREADY_REGISTERED) IPBconnect(&sessionB, ID_BOB, PASS_COMMON);
    
    res = IPBregister(&sessionC, ID_CHAR, PORT_CHARLIE, PASS_COMMON);
    if(res==IPB_ERROR_USER_ALREADY_REGISTERED) IPBconnect(&sessionC, ID_CHAR, PASS_COMMON);
    
    printf(GREEN " [PASS] Core Users Ready" RESET "\n");

    // --- 2. SECURITY ---
    print_header("2. Security");
    res = IPBregister(&sessionD, "Bad!ID", PORT_DAVE, PASS_COMMON); assert_failure("Reject Bad Chars", res);
    IPBclientSession sHack; IPBinitClientNetwork(&sHack, SERVER_IP, SERVER_PORT, 5099);
    res = IPBconnect(&sHack, ID_ALICE, 9999); assert_failure("Reject Bad Password", res);
    IPBcloseClientNetwork(&sHack);
    res = IPBsendMessage(&sessionA, ID_BOB, "Hack"); assert_failure("Reject Non-Friend Msg", res);

    // --- 3. SOCIAL GRAPH ---
    print_header("3. Social Graph");
    // Alice -> Bob (Friend Request)
    IPBsendFriendRequest(&sessionA, ID_BOB);
    // Check if UDP notification arrives (Count 1 -> "10")
    // If they are already friends from previous run, this might timeout if we don't handle logic,
    // but assert_failure above ensured they were NOT friends (msg rejected).
    verify_udp_strict(sessionB.socketUdpFD, CODE_FRIEND_REQ_IN, "10");
    
    IPBgetStream(&packet, &sessionB); // Bob reads req
    IPBacceptFriendRequest(&sessionB); // Bob accepts
    
    verify_udp_strict(sessionA.socketUdpFD, CODE_FRIEND_ACCEPTED, "10"); // Alice notified
    IPBgetStream(&packet, &sessionA); // Alice clears
    
    printf(GREEN " [PASS] Friendship Established (Alice <-> Bob)" RESET "\n");

    // --- 4. MESSAGING ---
    print_header("4. Messaging");
    res = IPBsendMessage(&sessionA, ID_BOB, "Hello");
    assert_success("Send Message", res);
    verify_udp_strict(sessionB.socketUdpFD, CODE_MESSAGE_IN, "10");
    IPBgetStream(&packet, &sessionB);
    printf(GREEN " [PASS] Message Received" RESET "\n");

    // --- 5. FLOODING ---
    print_header("5. Flooding");
    // Connect Bob -> Charlie
    IPBsendFriendRequest(&sessionB, ID_CHAR);
    verify_udp_strict(sessionC.socketUdpFD, CODE_FRIEND_REQ_IN, "10");
    IPBgetStream(&packet, &sessionC);
    IPBacceptFriendRequest(&sessionC);
    verify_udp_strict(sessionB.socketUdpFD, CODE_FRIEND_ACCEPTED, "10");
    IPBgetStream(&packet, &sessionB);

    // Alice -> Bob -> Charlie
    IPBflood(&sessionA, "FloodMsg");
    verify_udp_strict(sessionB.socketUdpFD, CODE_FLOOD_IN, "10");
    IPBgetStream(&packet, &sessionB);
    
    verify_udp_strict(sessionC.socketUdpFD, CODE_FLOOD_IN, "10");
    IPBgetStream(&packet, &sessionC);
    printf(GREEN " [PASS] Flood Propagation Correct" RESET "\n");

    // --- 6. SATURATION ---
    print_header("6. Buffer Saturation");
    printf("Sending 300 messages to Bob...\n");
    for(int i=0; i<300; i++) {
        char msg[20]; snprintf(msg, 20, "S%d", i);
        IPBsendMessage(&sessionA, ID_BOB, msg);
        if(i<299) { char b[512]; struct sockaddr_in f; socklen_t l=sizeof(f); recvfrom(sessionB.socketUdpFD, b, 512, 0, (struct sockaddr*)&f, &l); }
    }
    verify_udp_strict(sessionB.socketUdpFD, CODE_MESSAGE_IN, "FF"); // Max 255
    printf(GREEN " [PASS] Buffer Capped at 255" RESET "\n");
    
    // Drain
    int limit=300;
    while(limit-- > 0 && IPBgetStream(&packet, &sessionB) == IPB_OK && packet.type != MSG_STR_NO_CONTENT);

    // --- 7. MAX CLIENTS ---
    print_header("7. Max Clients");
    printf("Filling server...\n");
    char dID[9]; IPBclientSession dS;
    for(int i=0; i<105; i++) {
        IPBinitClientNetwork(&dS, SERVER_IP, SERVER_PORT, 6000+(i%100));
        snprintf(dID, 9, "User%04d", i);
        res = IPBregister(&dS, dID, 6000+(i%100), PASS_COMMON);
        IPBdisconnect(&dS); IPBcloseClientNetwork(&dS);
        if(res == IPB_ERROR_MAX_REACHED) {
            printf(GREEN " [PASS] Server Rejected User %d (Max Reached)" RESET "\n", i);
            break;
        }
    }

    // --- CLEANUP ---
    IPBdisconnect(&sessionA); IPBdisconnect(&sessionB); IPBdisconnect(&sessionC);
    IPBcloseClientNetwork(&sessionA); IPBcloseClientNetwork(&sessionB); IPBcloseClientNetwork(&sessionC);
    
    printf(GREEN "\n=== ALL TESTS PASSED SUCCESSFULLY ===" RESET "\n");
    return 0;
}